import streamlit as st

# Page configuration
st.set_page_config(
    page_title="TVS Inventory & Customer Catalog",
    page_icon="🏍️",
    layout="wide"
)

# Catalog database with clean studio/plain stock photos for each model
inventory_catalog = {
    "Apache RTR 160 2V Disc": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/Apache/Apache-RTR-160/Colors/glossy-black.png",
        "engine": "159.7 cc, Single Cylinder, 4-Stroke",
        "power": "16.04 PS @ 8400 rpm",
        "torque": "13.85 Nm @ 7000 rpm",
        "mileage": "45 - 50 kmpl",
        "braking": "Single Disc (Front), Drum (Rear)",
        "abs": "Single-Channel ABS",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "12 Litres",
        "colors": ["Glossy Black", "Matte Blue", "Tornado Black", "Pearl White", "Racing Red"]
    },
    "Apache RTR 160 2V Disc BT": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/Apache/Apache-RTR-160/Colors/glossy-black.png",
        "engine": "159.7 cc, Single Cylinder, 4-Stroke",
        "power": "16.04 PS @ 8400 rpm",
        "torque": "13.85 Nm @ 7000 rpm",
        "mileage": "45 - 50 kmpl",
        "braking": "Single Disc (Front), Drum (Rear)",
        "abs": "Single-Channel ABS",
        "connectivity": "Yes (SmartXonnect with Turn-by-Turn Navigation)",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "12 Litres",
        "colors": ["Matte Blue", "Glossy Black", "Pearl White"]
    },
    "Apache RTR 160 2V Disc BT Race Edition": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/Apache/Apache-RTR-160/Colors/glossy-black.png",
        "engine": "159.7 cc, Single Cylinder, 4-Stroke",
        "power": "16.04 PS @ 8400 rpm",
        "torque": "13.85 Nm @ 7000 rpm",
        "mileage": "45 - 50 kmpl",
        "braking": "Single Disc (Front), Drum (Rear)",
        "abs": "Single-Channel ABS",
        "connectivity": "Yes (SmartXonnect)",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "12 Litres",
        "colors": ["Matte Black (Race Edition Graphics)"]
    },
    "Apache RTR 160 4V Disc": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/Apache/Apache-RTR-160-4V/Colors/knight-black.png",
        "engine": "159.7 cc, 4-Valve, Oil-Cooled",
        "power": "17.55 PS @ 9250 rpm",
        "torque": "14.73 Nm @ 7250 rpm",
        "mileage": "40 - 45 kmpl",
        "braking": "Disc (Front), Disc (Rear)",
        "abs": "Single-Channel ABS",
        "connectivity": "Optional / Variant Dependent",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "12 Litres",
        "colors": ["Knight Black", "Lightning Blue", "Matte Black", "Racing Red"]
    },
    "Apache RTR 160 4V Disc LE Special Edition": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/Apache/Apache-RTR-160-4V/Colors/knight-black.png",
        "engine": "159.7 cc, 4-Valve, Oil-Cooled",
        "power": "17.55 PS @ 9250 rpm",
        "torque": "14.73 Nm @ 7250 rpm",
        "mileage": "40 - 45 kmpl",
        "braking": "Disc (Front), Disc (Rear)",
        "abs": "Single-Channel ABS",
        "connectivity": "Yes (SmartXonnect)",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "12 Litres",
        "colors": ["Lightning Blue (Special Edition Graphics)"]
    },
    "Raider Drum 125": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Raider/Colors/wicked-black.png",
        "engine": "124.8 cc, 3-Valve, Air-Oil Cooled",
        "power": "11.38 PS @ 7500 rpm",
        "torque": "11.2 Nm @ 6000 rpm",
        "mileage": "65 - 67 kmpl",
        "braking": "Drum (Front), Drum (Rear) with ET-Fi",
        "abs": "Sync Braking Technology (CBS)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Wicked Black", "Fiery Yellow"]
    },
    "Raider Disc 125 BSVI SS": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Raider/Colors/wicked-black.png",
        "engine": "124.8 cc, 3-Valve, Air-Oil Cooled",
        "power": "11.38 PS @ 7500 rpm",
        "torque": "11.2 Nm @ 6000 rpm",
        "mileage": "65 - 67 kmpl",
        "braking": "Disc (Front), Drum (Rear)",
        "abs": "Sync Braking Technology (CBS)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Striking Red", "Blazing Black"]
    },
    "Raider Disc 125 SX BT": {
        "category": "Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Raider/Colors/wicked-black.png",
        "engine": "124.8 cc, 3-Valve, Air-Oil Cooled",
        "power": "11.38 PS @ 7500 rpm",
        "torque": "11.2 Nm @ 6000 rpm",
        "mileage": "65 - 67 kmpl",
        "braking": "Disc (Front), Drum (Rear)",
        "abs": "Sync Braking Technology (CBS)",
        "connectivity": "Yes (SmartXonnect with TFT Screen & Voice Assist)",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Glossy Yellow", "Glossy Black"]
    },
    "XL 100 Heavy Duty Kick": {
        "category": "Moped",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-XL100/Colors/heavy-duty-i-touch-start.png",
        "engine": "99.7 cc, 4-Stroke, Single Cylinder",
        "power": "4.4 PS @ 6000 rpm",
        "torque": "6.5 Nm @ 3500 rpm",
        "mileage": "60 - 65 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "CBS (Combined Braking System)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "4 Litres",
        "colors": ["Black", "Blue", "Grey", "Red"]
    },
    "XL 100 HD Self": {
        "category": "Moped",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-XL100/Colors/heavy-duty-i-touch-start.png",
        "engine": "99.7 cc, 4-Stroke, Single Cylinder with Self Start",
        "power": "4.4 PS @ 6000 rpm",
        "torque": "6.5 Nm @ 3500 rpm",
        "mileage": "60 - 65 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "CBS (Combined Braking System)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "4 Litres",
        "colors": ["Matte Black", "Brown", "Red"]
    },
    "XL 100 Comfort / Winner Edition": {
        "category": "Moped",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-XL100/Colors/heavy-duty-i-touch-start.png",
        "engine": "99.7 cc, 4-Stroke, Single Cylinder",
        "power": "4.4 PS @ 6000 rpm",
        "torque": "6.5 Nm @ 3500 rpm",
        "mileage": "60 - 65 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "CBS (Combined Braking System)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "4 Litres",
        "colors": ["Winner Edition Special Graphics", "Teal Blue", "Mineral Purple"]
    },
    "Sports ES BSVI MWL": {
        "category": "Commuter Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Sport/Colors/black-blue.png",
        "engine": "109.7 cc, 4-Stroke, DuraLife Engine",
        "power": "8.29 PS @ 7350 rpm",
        "torque": "8.7 Nm @ 4500 rpm",
        "mileage": "70 - 73 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "Synchronized Braking Technology (SBT)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Black Blue", "Black Red", "Metallic Blue"]
    },
    "Sports ES BSVI MWL Graphics": {
        "category": "Commuter Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Sport/Colors/black-blue.png",
        "engine": "109.7 cc, 4-Stroke, DuraLife Engine",
        "power": "8.29 PS @ 7350 rpm",
        "torque": "8.7 Nm @ 4500 rpm",
        "mileage": "70 - 73 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "Synchronized Braking Technology (SBT)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Special Edition Premium Graphics Scheme"]
    },
    "Radeon BSVI ES MWL Drum": {
        "category": "Commuter Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Radeon/Colors/metal-black.png",
        "engine": "109.7 cc, ET-Fi Air-Cooled",
        "power": "8.19 PS @ 7350 rpm",
        "torque": "8.7 Nm @ 4500 rpm",
        "mileage": "68 - 73 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "Synchronized Braking Technology (SBT)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Metal Black", "Royal Blue", "Titanium Grey", "Stitch Beige"]
    },
    "Star City BSVI ES Drum": {
        "category": "Commuter Motorcycle",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Star-City-Plus/Colors/majestic-black.png",
        "engine": "109.7 cc, Ecothrust Fuel Injection (ET-Fi)",
        "power": "8.19 PS @ 7350 rpm",
        "torque": "8.7 Nm @ 4500 rpm",
        "mileage": "70 - 75 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "Synchronized Braking Technology (SBT)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "10 Litres",
        "colors": ["Majestic Black", "Grey-Blue", "Red-Black"]
    },
    "Jupiter 110 Drum Alloy": {
        "category": "Scooter",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Jupiter/Colors/titanium-grey.png",
        "engine": "113.3 cc, Single Cylinder, Air-Cooled",
        "power": "7.89 PS @ 6500 rpm",
        "torque": "9.8 Nm @ 5000 rpm",
        "mileage": "50 - 55 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "Sync Braking Technology (SBT)",
        "connectivity": "No",
        "bs_rating": "BS6 Phase 2",
        "fuel_tank": "6 Litres",
        "colors": ["Titanium Grey", "Midnight Black", "Mystic Gold"]
    },
    "Jupiter 110 Drum Alloy SXC Digital Meter": {
        "category": "Scooter",
        "image": "https://www.tvsmotor.com/-/media/Feature/Brands/TVS-Jupiter/Colors/titanium-grey.png",
        "engine": "113.3 cc, Single Cylinder, Air-Cooled",
        "power": "7.89 PS @ 6500 rpm",
        "torque": "9.8 Nm @ 5000 rpm",
        "mileage": "50 - 55 kmpl",
        "braking": "Drum (Front), Drum (Rear)",
        "abs": "
